# Generated by Django 5.0.14 on 2026-07-30 16:37

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('product', 'Product'), ('business', 'Business'), ('creative', 'Creative'), ('technical', 'Technical'), ('research', 'Research')], default='product', max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('insane', 'Insane')], default='moderate', max_length=20)),
                ('deadline', models.DateField()),
                ('target_hours', models.DecimalField(decimal_places=2, max_digits=8, validators=[apps.core.validators.validate_positive])),
                ('expected_daily_hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[apps.core.validators.validate_positive])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('github_repository', models.URLField(blank=True)),
                ('progress_percent', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_percentage])),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='FailureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField(blank=True)),
                ('days_lost', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_records', to='projects.project')),
            ],
            options={
                'ordering': ['-failure_date'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='projects_pr_owner_i_4798b7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deadline'], name='projects_pr_deadlin_bd2912_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'status'], name='projects_pr_is_acti_189799_idx'),
        ),
        migrations.AddIndex(
            model_name='failurerecord',
            index=models.Index(fields=['project', 'failure_date'], name='projects_fa_project_68f953_idx'),
        ),
    ]
