# Generated by Django 6.0.7 on 2026-07-31 05:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='failurerecord',
            name='failure_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
