# Generated by Django 5.2.16 on 2026-07-31 07:37

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_start_date_alter_failurerecord_failure_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='running', max_length=20)),
                ('active_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('paused_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('total_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('focus_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='execution.focussession')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_active_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('total_paused_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('total_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('focus_sessions_count', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_positive])),
                ('average_session_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('longest_session_seconds', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'log_date'), name='unique_daily_work_summary_per_day')],
            },
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['owner', 'started_at'], name='execution_f_owner_i_ac3340_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['project', 'started_at'], name='execution_f_project_b589cc_idx'),
        ),
    ]
