# Generated by Django 5.2.16 on 2026-07-31 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='idle_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='focussession',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sessionpause',
            name='reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
