# Generated by Django 5.2.16 on 2026-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_focussession_idle_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focussession',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='running', max_length=20),
        ),
    ]
