# Generated by Django 5.2.16 on 2026-08-01 17:37

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_alter_focussession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='break_duration',
            field=models.PositiveIntegerField(default=300, validators=[apps.core.validators.validate_positive]),
        ),
        migrations.AddField(
            model_name='focussession',
            name='completed_cycles',
            field=models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='focussession',
            name='current_phase',
            field=models.CharField(choices=[('work', 'Work'), ('short_break', 'Short break'), ('long_break', 'Long break')], default='work', max_length=20),
        ),
        migrations.AddField(
            model_name='focussession',
            name='cycle_number',
            field=models.PositiveIntegerField(default=1, validators=[apps.core.validators.validate_positive]),
        ),
        migrations.AddField(
            model_name='focussession',
            name='interruptions',
            field=models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='focussession',
            name='long_break_duration',
            field=models.PositiveIntegerField(default=900, validators=[apps.core.validators.validate_positive]),
        ),
        migrations.AddField(
            model_name='focussession',
            name='long_break_every',
            field=models.PositiveIntegerField(default=4, validators=[apps.core.validators.validate_positive]),
        ),
        migrations.AddField(
            model_name='focussession',
            name='paused_time',
            field=models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='focussession',
            name='phase_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='focussession',
            name='work_duration',
            field=models.PositiveIntegerField(default=1500, validators=[apps.core.validators.validate_positive]),
        ),
        migrations.CreateModel(
            name='FocusSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='timeline', max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('focus_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='execution.focussession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
