# Generated by Django 5.0.14 on 2026-07-30 16:37

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('focus_minutes', models.PositiveIntegerField(default=25, validators=[apps.core.validators.validate_positive])),
                ('break_minutes', models.PositiveIntegerField(default=5, validators=[apps.core.validators.validate_positive])),
                ('interruptions', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('completed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6, validators=[apps.core.validators.validate_non_negative])),
                ('tasks_finished', models.PositiveIntegerField(default=0)),
                ('github_commits', models.PositiveIntegerField(default=0)),
                ('screenshot_proof', models.FileField(blank=True, null=True, upload_to='screenshots/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True)),
                ('energy_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('peak', 'Peak')], default='medium', max_length=20)),
                ('distractions', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['owner', 'log_date'], name='tracker_dai_owner_i_5dfc31_idx'), models.Index(fields=['project', 'log_date'], name='tracker_dai_project_535e31_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('owner', 'project', 'log_date'), name='unique_daily_log_per_day'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['owner', 'started_at'], name='tracker_pom_owner_i_96a195_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['project', 'started_at'], name='tracker_pom_project_740b49_idx'),
        ),
    ]
