# Generated by Django 5.0.14 on 2026-07-30 16:37

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reality_report', models.TextField()),
                ('success_probability', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_percentage])),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('projected_failure_date', models.DateField(blank=True, null=True)),
                ('average_hours_needed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recovery_plan', models.TextField(blank=True)),
                ('verdict', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('stable', 'Stable')], default='warning', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('daily_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='tracker.dailylog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['owner', 'generated_at'], name='ai_judge_ai_owner_i_9c2c63_idx'), models.Index(fields=['daily_log', 'generated_at'], name='ai_judge_ai_daily_l_89a6a9_idx')],
            },
        ),
    ]
