# Generated by Django 5.0.14 on 2026-07-30 16:37

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[apps.core.validators.validate_non_negative])),
                ('progress_score', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_percentage])),
                ('failures', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('success_percentage', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_percentage])),
                ('budget_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[apps.core.validators.validate_non_negative])),
                ('pressure_level', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_percentage])),
                ('commits', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('focus_time_minutes', models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative])),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('30_day_streak', '30 Day Streak'), ('100_hours', '100 Hours'), ('no_failure_month', 'No Failure Month'), ('impossible_project', 'Complete Impossible Project'), ('500_hours', '500 Hours')], max_length=40)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['owner', 'earned_at'], name='analytics_a_owner_i_f843d9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('owner', 'achievement_type'), name='unique_achievement_per_user'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['owner', 'updated_at'], name='analytics_s_owner_i_3475ac_idx'),
        ),
    ]
