# Generated by Django 6.0.7 on 2026-08-02 03:25

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_xp_to_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('30_day_streak', '30 Day Streak'), ('100_hours', '100 Hours'), ('no_failure_month', 'No Failure Month'), ('impossible_project', 'Complete Impossible Project'), ('500_hours', '500 Hours'), ('first_session', 'First Session'), ('focus_flow', 'Focus Flow'), ('full_throttle', 'Full Throttle'), ('project_architect', 'Project Architect'), ('legend', 'Legend'), ('hall_of_victory', 'Hall of Victory')], max_length=40),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='xp',
            field=models.PositiveIntegerField(default=0, validators=[apps.core.validators.validate_non_negative]),
        ),
    ]
