# Generated by Django 5.0.14 on 2026-07-30 16:37

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.core.validators.validate_non_negative])),
                ('change_type', models.CharField(choices=[('initial', 'Initial'), ('deduction', 'Deduction'), ('reset', 'Reset'), ('adjustment', 'Adjustment')], default='initial', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[apps.core.validators.validate_non_negative])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='budget_budg_owner_i_b2bb3d_idx')],
            },
        ),
    ]
